// A hand-curated starter vocabulary, not a complete CET-4 syllabus.
const CHAPTERS = [
 ['🌱','启程草原','A new beginning','achieve|v. 实现；达到;adapt|v. 适应；改编;benefit|n. 益处；v. 受益;challenge|n. 挑战;effort|n. 努力;goal|n. 目标;improve|v. 改善；提高;opportunity|n. 机会;progress|n. 进步;purpose|n. 目的;require|v. 需要；要求;success|n. 成功'],
 ['🏫','校园小镇','Campus life','academic|adj. 学术的;assignment|n. 作业；任务;attend|v. 出席；参加;campus|n. 校园;course|n. 课程;degree|n. 学位；程度;discipline|n. 纪律；学科;graduate|v. 毕业;lecture|n. 讲座；课;major|n. 专业；adj. 主要的;scholarship|n. 奖学金;semester|n. 学期'],
 ['🌲','思考森林','Ideas and opinions','analyze|v. 分析;assume|v. 假定；认为;concept|n. 概念;consider|v. 考虑;convince|v. 使确信；说服;doubt|n. 怀疑;evidence|n. 证据;explain|v. 解释;identify|v. 识别；确定;logical|adj. 符合逻辑的;opinion|n. 意见；看法;prove|v. 证明'],
 ['🌊','交流海岸','Connect with others','communicate|v. 沟通；交流;conflict|n. 冲突;contact|n. 联系；v. 联系;cooperate|v. 合作;debate|n. 辩论；v. 辩论;discuss|v. 讨论;express|v. 表达;interaction|n. 互动；相互作用;negotiate|v. 谈判；协商;persuade|v. 说服;respond|v. 回应；回答;relationship|n. 关系'],
 ['🌿','生态湿地','Our living planet','climate|n. 气候;conserve|v. 保护；节约;consume|v. 消耗；消费;environment|n. 环境;habitat|n. 栖息地;natural|adj. 自然的;pollution|n. 污染;preserve|v. 保存；保护;recycle|v. 回收利用;resource|n. 资源;species|n. 物种;sustainable|adj. 可持续的'],
 ['⚡','科技之城','Science and technology','access|n. 通道；v. 获取;artificial|adj. 人工的;automatic|adj. 自动的;device|n. 设备；装置;digital|adj. 数字的;efficient|adj. 高效的;experiment|n. 实验;innovation|n. 创新;network|n. 网络;process|n. 过程；v. 处理;technical|adj. 技术的;technology|n. 技术；科技'],
 ['💼','贸易港口','Work and economy','account|n. 账户；描述;budget|n. 预算;career|n. 职业；事业;commercial|adj. 商业的;compete|v. 竞争;demand|n. 需求；v. 要求;employ|v. 雇用；使用;expense|n. 费用;income|n. 收入;invest|v. 投资;profit|n. 利润；益处;supply|n. 供应；v. 提供'],
 ['🏥','健康山谷','A healthy life','anxiety|n. 焦虑;balance|n. 平衡；v. 平衡;depression|n. 抑郁；萧条;disease|n. 疾病;emotion|n. 情绪；情感;exercise|n. 锻炼；练习;fatigue|n. 疲劳;mental|adj. 精神的；心理的;nutrition|n. 营养;physical|adj. 身体的；物理的;recover|v. 恢复；康复;treatment|n. 治疗；对待'],
 ['🏛️','社会古都','People and society','citizen|n. 公民;community|n. 社区；群体;culture|n. 文化;diverse|adj. 多种多样的;equal|adj. 平等的；相等的;individual|n. 个人；adj. 个别的;justice|n. 公正；司法;policy|n. 政策；方针;population|n. 人口;responsibility|n. 责任;tradition|n. 传统;volunteer|n. 志愿者；v. 自愿做'],
 ['⛰️','探索高地','Explore the world','abandon|v. 放弃；遗弃;approach|v. 接近；n. 方法;capture|v. 捕获；夺取;destination|n. 目的地;discover|v. 发现;distance|n. 距离;encounter|v. 遭遇；n. 相遇;explore|v. 探索;journey|n. 旅程;locate|v. 确定位置;observe|v. 观察；遵守;survive|v. 幸存；生存'],
 ['🌙','写作星桥','Words that matter','accurate|adj. 准确的;adequate|adj. 足够的；适当的;apparent|adj. 明显的；表面上的;complex|adj. 复杂的;essential|adj. 必不可少的;frequent|adj. 频繁的;obvious|adj. 明显的;potential|adj. 潜在的；n. 潜力;relevant|adj. 相关的;significant|adj. 显著的；重要的;sufficient|adj. 足够的;unique|adj. 独特的'],
 ['🏆','四级冠军路','The final challenge','accomplish|v. 完成；实现;acknowledge|v. 承认；致谢;advantage|n. 优势；有利条件;consequence|n. 结果；后果;contribute|v. 贡献；促成;demonstrate|v. 证明；展示;evaluate|v. 评价；评估;maintain|v. 维持；维修;participate|v. 参与;promote|v. 促进；提升;recognize|v. 认出；认可;strategy|n. 策略']
].map(([icon,name,english,raw],unit)=>({icon,name,english,words:raw.split(';').map((row,j)=>{const [word,meaning]=row.split('|');return {id:unit*12+j,word,meaning,unit};})}));
const WORDS=CHAPTERS.flatMap(c=>c.words);
const LEGENDS=[[144,'急冻鸟',200],[145,'闪电鸟',200],[146,'火焰鸟',200],[150,'超梦',250],[151,'梦幻',250],[243,'雷公',200],[244,'炎帝',200],[245,'水君',200],[249,'洛奇亚',250],[250,'凤王',250],[251,'时拉比',250],[377,'雷吉洛克',200],[378,'雷吉艾斯',200],[379,'雷吉斯奇鲁',200],[382,'盖欧卡',250],[383,'固拉多',250],[384,'烈空坐',300]];
const RARES=[[25,'皮卡丘',80],[133,'伊布',90],[143,'卡比兽',120],[147,'迷你龙',100],[196,'太阳伊布',130],[197,'月亮伊布',130],[113,'吉利蛋',100],[123,'飞天螳螂',110],[280,'拉鲁拉丝',80],[359,'阿勃梭鲁',130],[371,'宝贝龙',110],[302,'勾魂眼',90]];
const NORMALS=[[1,'妙蛙种子',50],[4,'小火龙',50],[7,'杰尼龟',50],[10,'绿毛虫',30],[16,'波波',30],[19,'小拉达',30],[35,'皮皮',50],[37,'六尾',50],[39,'胖丁',50],[41,'超音蝠',30],[43,'走路草',30],[54,'可达鸭',50],[58,'卡蒂狗',60],[63,'凯西',50],[66,'腕力',40],[74,'小拳石',40],[92,'鬼斯',50],[95,'大岩蛇',60],[104,'卡拉卡拉',50],[129,'鲤鱼王',30],[152,'菊草叶',50],[155,'火球鼠',50],[158,'小锯鳄',50],[163,'咕咕',30],[179,'咩利羊',50],[202,'果然翁',50],[252,'木守宫',50],[255,'火稚鸡',50],[258,'水跃鱼',50],[261,'土狼犬',30],[263,'蛇纹熊',30],[265,'刺尾虫',30],[270,'莲叶童子',40],[304,'可可多拉',50],[333,'青绵鸟',50]];
const POKEMON=[...LEGENDS.map(x=>[...x,'legend']),...RARES.map(x=>[...x,'rare']),...NORMALS.map(x=>[...x,'normal'])].map(([id,name,cost,category])=>({id,name,cost,category}));
const ITEMS=[{id:'poke-ball',name:'精灵球',cost:15,chance:.60},{id:'great-ball',name:'超级球',cost:30,chance:.80},{id:'ultra-ball',name:'高级球',cost:50,chance:.95},{id:'potion',name:'伤药',cost:10,chance:0}];
